### ISSUE TITLE
Should #keys be available given #key? exists

### ISSUE THREAD

**Issue by jeremyf** [dry-rb/dry-container#12]
Given that `Dry::Container::Resolver#key?` exists, I was anticipating that `Dry::Container::Resolver#keys` would also exist.

**Comment by solnic** [comment]
Yes it should be there, I already do `_container.keys` in a couple of places :( /cc @AMHOL

**Comment by jeremyf** [comment]
I'm working on the pull request. There is a rubocop violation, so I'm piecemealing two commits for this.

**Comment by jeremyf** [comment]
Rubocop updated its minor version since the last test was run against dry-container
