### ISSUE TITLE
Custom resolver using lambda seems not to conform to the resolver interface.

### ISSUE THREAD

**Issue by yewton** [dry-rb/dry-container#39]
Custom resolver using lambda examples are shown in [the document](http://dry-rb.org/gems/dry-container/registry-and-resolver/#customization) .
But it seems that resolvers are supposed to respond to more messages other than `#call` (cf. https://github.com/dry-rb/dry-container/blob/v0.6.0/lib/dry/container/resolver.rb , https://github.com/dry-rb/dry-container/blob/v0.6.0/lib/dry/container/mixin.rb ).

**Comment by AMHOL** [comment]
Thank you, the docs are quite old, I'll try to get around to updating that soon.

**Comment by yewton** [comment]
It seems the docs are not valid since 2 years ago https://github.com/dry-rb/dry-container/commit/7f905a634897c0dc03a24b58172ea9b17a24677b 🤔 

So what is the correct way to define custom resolvers?
Subclassing `::Dry::Container::Resolver` ?

Or, custom resolvers are not supported anymore...?

**Comment by AMHOL** [comment]
@yewton yes, subclassing should work, or just adhering to the same interface, the old interface used to just be `#call` but it got updated since then

**Comment by yewton** [comment]
Thank you! I'll give it a shot.

**Comment by GustavoCaso** [comment]
@yewton Thanks so much for pointing out the outdated docs.

Could be really useful if you could share how are you using custom `resolver` and `registry` in your current project. We are evaluating if the feature is worth keeping. 😄

**Comment by yewton** [comment]
@GustavoCaso Thanks for your reply!

In fact, I don't use custom `resolver/registry` anymore 😓 

At first I wanted to achieve something like an "automatic resolver" in my Rails project, and tried to write a custom resolver that uses Rails' autoloading feature.
But I realized that such resolving processes should not be done in runtime, but should be done at startup time with "automatic registerer", like `dry-system`.

So now I cannot imagine any custom `resolver/registry` use cases...
I suspect that they are no longer needed 😰

**Comment by flash-gordon** [comment]
See https://github.com/dry-rb/dry-container/issues/49#issuecomment-460263196
