### ISSUE TITLE
What do think about introduction of interceptors for instantiated services?

### ISSUE THREAD

**Issue by zekefast** [dry-rb/dry-container#40]
I thinking about preparation of PR for addition of interceptors. It would be interested to know how likely PR with this kind of feature could be merged.

This feature already present in different implementations of containers in Ruby and other languages.
Essentially this is a wrapper around instance of service added before returning the service to a client.

Interceptors are great way to implement service instantiation tracers, loggers, exception handlers, authorization checks and many other auxiliary functionality which correspond the instance.

**Comment by AMHOL** [comment]
@zekefast do you have an example of how that would look? Is it basically just a decorator around the registered item?

**Comment by zekefast** [comment]
@AMHOL I would say more like a Proxy than Decorator, because Interceptor is intended to preserve interface of original item at least for the container's callers.

The DSL/methods we can adapt to make it feel natural for `dry-container`, but you can see implemented and described idea in [Needle](https://web.archive.org/web/20160405072449/http://needle.rubyforge.org/chapter-5.html) by Jamis Buck.

I'm hosting and fixing bugs in it for some time already on [GitHub](https://github.com/zekefast/needle/tree/porting_to_ruby_2.4.0). I used it for my projects where possible. It's very powerful, but I would like to see something more widely accepted.

`dry-container` is much simple and, probably, as result much faster especially on large graph of instances then Needle.

So I rather submit PRs to `dry-container` then make rewrite of Needle.

Please, let me know if you need more information or want to discuss anything. I can go to chat as well if it would be simpler.

**Comment by zekefast** [comment]
Hello @AMHOL, do you have any ideas about my above messages?

**Comment by AMHOL** [comment]
@zekefast definitely interesting, does it have any use outside of instrumentation? Be interested to see what @solnic @timriley @flash-gordon @GustavoCaso think.

**Comment by solnic** [comment]
I think this is a good idea. I wanted to add something like that to dry-system, but I'm OK with having this here.

**Comment by timriley** [comment]
Agreed! I look forward to having a feature like this, and I'm happy to see it explored here first :)

**Comment by zekefast** [comment]
@AMHOL, under instrumentation do you mean tracers and loggers? It can be used any where where you want transparently add side behavior to your logic. For example, it could be API client caches which you could add to prevent calls propagation inside library code, it could be ACLs to manage access to some object or particular class of objects, it could be some flavor of aspect-oriented programming where you focus on addition cross objects functionality. But I thing I still missed many other examples of its usage.

@solnic, @timriley thank you guys for the interest in this feature. Then I will prepare a pull request with it then.

**Comment by solnic** [comment]
I added a plugin to dry-system that does exactly this. Please take a look [here](https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/plugins/decorate.rb). This could be ported (and probably improved) to dry-container.

**Comment by GustavoCaso** [comment]
@zekefast have you started working on this one?

**Comment by zekefast** [comment]
@GustavoCaso Yes, but haven't completed yet. There was a bit distraction from OSS activity during holidays to family rituals :)

**Comment by GustavoCaso** [comment]
@zekefast completely understandable. If you need any help do not hesitate to ask 😄

**Comment by flash-gordon** [comment]
Addressed in https://github.com/dry-rb/dry-container/pull/50
