### ISSUE TITLE
Support for mocking

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-container#6]
I think it would be useful to have a public API for mocking. Currently I mutate internal `_container` object in a couple special places in my test suite where there's really no other way than to mock a dependency via container.

**Comment by AMHOL** [comment]
How come you can't just register different objects based on the environment?

**Comment by solnic** [comment]
Because I only need that in a couple of specs. This is conditional behavior, I do `it "does things", mock_foo: true` and then I need to handle mocking in `before(:each, mock_foo: true)`.

I think in general it would be great to come up with a strategy for mocking objects that container resolves. It's especially painful in controller specs where we don't have DI at all (rails...:()

**Comment by sagmor** [comment]
Closed by #11 :smile:
