### ISSUE TITLE
Fix incorrect version listed in docs

### ISSUE THREAD

**Issue by bkuhlmann** [dry-rb/dry-container#75]
## Describe the bug

Noticed, when trying to install Dry Container 0.8.0, that it doesn't exist. Only 0.7.2 is the latest version at the time of this writing. By the way, this seems to be an oddity with other Dry libraries in case it's of interest. It seems the generated documentation is ahead of what is available.

## To Reproduce

Visit the [landing page](https://dry-rb.org/gems/dry-container/0.8) (also notice `0.8` is in the URL as well). Here's a screenshot for illustration:

![Firefox-ps0t0imc](https://user-images.githubusercontent.com/50245/117093370-fa4ded80-ad1d-11eb-808a-e5b2829e8964.png)

## Expected behavior

Would expect 0.7.2 to be listed instead of 0.8.0 as found on [RubyGems](https://rubygems.org/gems/dry-container).

## My environment

Using Firefox as my browser.

**Comment by solnic** [comment]
Thanks for reporting this. It should be fixed now.

> By the way, this seems to be an oddity with other Dry libraries in case it's of interest.

Which ones?

**Comment by bkuhlmann** [comment]
:bow: **Piotr**. Yeah, so here's what I found (well, in reverse of what I was reporting above, I guess):

- **Dry Configurable** - Listed as 0.11.0 in the docs but 0.12.1 is available on RubyGems.
- **Dry Core** - Listed as 0.4.0 but 0.5.0 is available on RubyGems.
- **Dry Equalizer** - Listed as 0.2.0 but 0.3.0 is available on RubyGems.
- **Dry Events** - Listed as 0.2.0 but 0.3.0 is available on RubyGems.
- **Dry Inflector** - LIsted as 0.1.0 but 0.2.0 is available on RubyGems.
- **Dry Matcher** - Listed as 0.8.0 but 0.9.0 is available on RubyGems.
- **Dry Schema** - Listed as 1.5.0 but 1.6.2 is available on RubyGems.
- **Dry Struct** - Listed as 1.0.0 but 1.4.0 is available on RubyGems.
- **Dry Types** - Listed as 1.2.0 but 1.5.0 is available on RubyGems.

**Comment by solnic** [comment]
@bkuhlmann thanks, it's unfortunate :( I haven't automated creation of new release branches and that's how we ended up with this. I'll create missing branches, thanks for preparing this list, very helpful!

**Comment by flash-gordon** [comment]
@solnic I think the bigger problem it's not documented, e.g. I don't remember what should be done to cut a doc release.

**Comment by solnic** [comment]
@flash-gordon a new tag == a new docsite, doesn't matter if things changed or not. Then every push to docsite in a release branch will result in docsite deployment on dry-rb.org

**Comment by flash-gordon** [comment]
@solnic what is "docsite"? :(

**Comment by solnic** [comment]
@flash-gordon directory in a repo 🙂

**Comment by flash-gordon** [comment]
@solnic I cannot decode "a new tag == a new docsite" then. A new directory?

**Comment by solnic** [comment]
@flash-gordon oh sorry for the confusion. I meant that every new **major or minor** tag must result in a corresponding `release-x.y` branch that must include the docsite dir. This part **is not automated** that's why we ended up with inconsistencies.

**Comment by flash-gordon** [comment]
@solnic I have such a branch https://github.com/dry-rb/dry-monads/tree/release-1.4 but there's no 1.4 in the docs https://dry-rb.org/gems/dry-monads/1.3/ Do you what I missed?
