### ISSUE TITLE
Strings and Symbols

### ISSUE THREAD

**Issue by sagmor** [dry-rb/dry-container#8]
I believe it would make sense to cast keys into strings

Right now the following happens if you switch between Symbols and Strings:

``` ruby
container = Dry::Container.new
container.register(:foo, 'bar')
container[:foo]
# => "bar"
container['foo']
# => Dry::Container::Error: Nothing registered with the key "foo"
```

The confusion appears when you start to namespace things, for example:

``` ruby
container = Dry::Container.new
container.namespace(:test) do
  register(:foo, 'bar')
end

# Now it's a string
container['test.foo']
# => "bar"
```

I think it would be clearer if things got stored as strings by default.
If you think that's better I can push a PR with the change.

**Comment by solnic** [comment]
I agree, consistency FTW
