### ISSUE TITLE
Getting an `ArgumentError` missing keywords on Ruby 2.7.3

### ISSUE THREAD

**Issue by FictMan** [dry-rb/dry-container#87]
## Describe the bug

After updating `dry-container` from 0.8.0 to 0.10.0, I'm getting an ArgumentError missing keywords in `mixin.rb`
```
dry-container-0.10.0/lib/dry/container/mixin.rb:221:in `key?': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

## My environment

- Ruby version: 2.7.3
- Rails version: 7.x
- OS: Mojave 12.4

**Comment by flash-gordon** [comment]
Please demonstrate a reproducible case, otherwise, I think this is an issue in your code. Keep in mind, 0.10 can have breaking changes compared to 0.8.

**Comment by FictMan** [comment]
My bad, because when i'm trying use next code:
```
require 'dry/schema'

Dry::Schema.load_extensions(:hints)

.....
```

it cause for `dry-container` here is error
```
Failure/Error: require 'dry/schema'
ArgumentError:
  wrong number of arguments (given 2, expected 1)
# ./vendor/ruby/2.7.0/gems/dry-container-0.10.0/lib/dry/container/mixin.rb:221:in `key?'
```

Versions:
- dry-schema (1.3.4)
- dry-container (0.10.1)

**Comment by flash-gordon** [comment]
Unfortunately, it's not enough to understand what went wrong. Can you provide a bull backtrace or a sample code that's failing? So that I can reproduce it on my side.

**Comment by farooqch11** [comment]
#92  is this relivent to this ?

**Comment by flash-gordon** [comment]
Dunno but this one should be closed for lack of info 😅
